name: Build and Test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./FSM
    - name: Build
      run: dotnet build ./FSM --no-restore
    - name: Test
      run: dotnet test ./FSM --no-build --verbosity normal
    - name: Bump versions
      uses: michmich112/version-bumper@master
      with:
        options-file: '.github/versions-bumper/options.json'
        github-token: ${{ secrets.GITHUB_TOKEN }}
